# logging.yaml file for use with drive_manager.py & plot_manager.py v1
# 2021-03-15

version: 1
disable_existing_loggers: False

formatters:
    console:
        format: "%(message)s"
    console_expanded:
        format: '%(module)2s:%(lineno)s - %(funcName)3s: %(levelname)3s:    %(message)s'
    standard:
        format: '%(asctime)s - %(module)2s:%(lineno)s - %(funcName)3s: %(levelname)3s %(message)s'
    error:
        format: "%(levelname)s <PID %(process)d:%(processName)s> %(module)s.%(funcName)s(): %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        formatter: console_expanded
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: standard
        filename: /home/mmv/mining/plot_manager/logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: /home/mmv/mining/plot_manager/logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: standard
        filename: /home/mmv/mining/plot_manager/logs/debug.log
        maxBytes: 10485760
        backupCount: 2
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: standard
        filename: /home/mmv/mining/plot_manager/logs/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    warning_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: standard
        filename: /home/mmv/mining/plot_manager/logs/warning.log
        maxBytes: 10485760 # 10MB
        backupCount: 2
        encoding: utf8

    plot_manager_handler:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: /home/mmv/mining/plot_manager/logs/plot_manager.log
      maxBytes: 10485760 # 10MB
      backupCount: 2
      encoding: utf8

root:
    level: NOTSET
    handlers:
    propogate: no

loggers:
    __main__:
        handlers: [console, info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warning_file_handler, plot_manager_handler]
        propogate: no
